[workspace]
members = [
    "bpf-sys",
    "cargo-bpf",
    "examples/example-probes",
    "examples/example-userspace",
    "redbpf-macros",
    "redbpf-probes",
    "redbpf-tools",
    "redbpf-xdp",
    "redbpf",
]
